# Generated by Django 5.2.6 on 2025-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_assets/default_img.jpg', null=True, upload_to='event_assets'),
        ),
    ]
